# Base the DynamoDB B'n'R docker container on python 3
FROM python:3.5

# Add the tool directory
ADD . /dynamobnr

# Set work directory
WORKDIR /dynamobnr

# Install the tool and clean the work directory
RUN \
  python setup.py install && \
  rm -rf /dynamobnr && \
  mkdir /dynamobnr
